import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const races = [
  {
    title: "도쿄 마라톤 2025",
    titleEn: "Tokyo Marathon 2025",
    description: "세계 6대 마라톤 중 하나인 도쿄 마라톤. 도쿄의 명소를 달리며 42.195km를 완주하세요.",
    eventDate: new Date("2025-03-02"),
    eventTime: "오전 09:00 JST",
    country: "일본",
    region: "관동 지방",
    city: "도쿄",
    venue: "도쿄 도청",
    address: "일본 도쿄도 신주쿠구 니시신주쿠 2-8-1",
    registrationStatus: "접수 중",
    registrationStart: new Date("2024-08-01"),
    registrationEnd: new Date("2025-01-31"),
    categories: ["풀 마라톤", "10K 펀런"],
    organizer: "도쿄 마라톤 재단",
    organizerRep: "야마다 타로",
    phone: "+81 3-5555-5555",
    email: "info@tokyo-marathon.com",
    website: "https://www.marathon.tokyo",
    imageUrl: "https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?w=800",
    isFeatured: true,
    isUrgent: true,
  },
  {
    title: "보스턴 퀄리파이어 오픈",
    titleEn: "Boston Qualifier Open",
    description: "보스턴 마라톤 자격을 취득할 수 있는 공인 대회입니다.",
    eventDate: new Date("2025-04-15"),
    eventTime: "오전 07:00 EST",
    country: "미국",
    region: "동부",
    city: "매사추세츠",
    venue: "홉킨턴 시작점",
    address: "Hopkinton, MA, USA",
    registrationStatus: "접수 중",
    registrationStart: new Date("2024-10-01"),
    registrationEnd: new Date("2025-03-01"),
    categories: ["풀 마라톤"],
    organizer: "Boston Athletic Association",
    phone: "+1 617-236-1652",
    email: "info@baa.org",
    website: "https://www.baa.org",
    imageUrl: "https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "마운틴 트레일 챌린지",
    titleEn: "Mountain Trail Challenge",
    description: "록키 마운틴의 아름다운 자연을 달리는 트레일 러닝 대회입니다.",
    eventDate: new Date("2025-05-20"),
    eventTime: "오전 06:00 MST",
    country: "미국",
    region: "서부",
    city: "콜로라도",
    venue: "Rocky Mountain National Park",
    address: "1000 US-36, Estes Park, CO 80517",
    registrationStatus: "얼리버드",
    registrationStart: new Date("2024-11-01"),
    registrationEnd: new Date("2025-04-01"),
    categories: ["50K 울트라", "25K 트레일", "10K 트레일"],
    organizer: "Mountain Running Club",
    email: "contact@mountaintrail.run",
    website: "https://mountaintrail.run",
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "시티 하프 마라톤",
    titleEn: "NYC Half Marathon",
    description: "뉴욕 맨해튼을 관통하는 하프 마라톤 대회입니다.",
    eventDate: new Date("2025-06-10"),
    eventTime: "오전 07:30 EST",
    country: "미국",
    region: "동부",
    city: "뉴욕",
    venue: "센트럴 파크",
    address: "Central Park, New York, NY",
    registrationStatus: "대기 접수",
    registrationStart: new Date("2024-12-01"),
    registrationEnd: new Date("2025-05-01"),
    categories: ["하프 마라톤"],
    organizer: "New York Road Runners",
    phone: "+1 212-423-2249",
    email: "help@nyrr.org",
    website: "https://www.nyrr.org",
    imageUrl: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "레드우드 포레스트 런",
    titleEn: "Redwood Forest Run",
    description: "거대한 레드우드 숲 사이를 달리는 환상적인 러닝 경험을 제공합니다.",
    eventDate: new Date("2025-08-22"),
    eventTime: "오전 08:00 PST",
    country: "미국",
    region: "서부",
    city: "캘리포니아",
    venue: "Muir Woods National Monument",
    address: "1 Muir Woods Rd, Mill Valley, CA 94941",
    registrationStatus: "접수 중",
    registrationStart: new Date("2025-01-01"),
    registrationEnd: new Date("2025-07-15"),
    categories: ["하프 마라톤", "10K", "5K 펀런"],
    organizer: "California Trail Runners",
    email: "info@redwoodrun.com",
    website: "https://redwoodrun.com",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "서울 국제 마라톤",
    titleEn: "Seoul International Marathon",
    description: "서울의 중심부를 달리는 대한민국 대표 마라톤 대회입니다.",
    eventDate: new Date("2025-03-16"),
    eventTime: "오전 08:00 KST",
    country: "한국",
    region: "수도권",
    city: "서울",
    venue: "광화문 광장",
    address: "서울특별시 종로구 세종대로 172",
    registrationStatus: "접수 중",
    registrationStart: new Date("2024-11-01"),
    registrationEnd: new Date("2025-02-28"),
    categories: ["풀 마라톤", "하프 마라톤", "10K"],
    organizer: "대한육상연맹",
    phone: "+82 2-414-3036",
    email: "info@seoul-marathon.com",
    website: "https://seoul-marathon.com",
    imageUrl: "https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=800",
    isFeatured: true,
    isUrgent: false,
  },
  {
    title: "오사카 시티 런",
    titleEn: "Osaka City Run",
    description: "오사카의 활기찬 도심을 달리는 시민 마라톤입니다.",
    eventDate: new Date("2025-11-23"),
    eventTime: "오전 09:00 JST",
    country: "일본",
    region: "간사이 지방",
    city: "오사카",
    venue: "오사카 성",
    address: "1-1 Osakajo, Chuo Ward, Osaka",
    registrationStatus: "접수 중",
    registrationStart: new Date("2025-06-01"),
    registrationEnd: new Date("2025-10-31"),
    categories: ["풀 마라톤", "하프 마라톤", "7K 펀런"],
    organizer: "오사카 마라톤 협회",
    email: "info@osaka-marathon.jp",
    website: "https://www.osaka-marathon.com",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "베를린 마라톤",
    titleEn: "Berlin Marathon",
    description: "세계 기록이 가장 많이 나온 평탄한 코스의 베를린 마라톤입니다.",
    eventDate: new Date("2025-09-28"),
    eventTime: "오전 09:15 CET",
    country: "유럽",
    region: "독일",
    city: "베를린",
    venue: "브란덴부르크 문",
    address: "Pariser Platz, 10117 Berlin, Germany",
    registrationStatus: "마감",
    registrationStart: new Date("2024-10-01"),
    registrationEnd: new Date("2024-12-31"),
    categories: ["풀 마라톤"],
    organizer: "SCC Events",
    phone: "+49 30 301288-0",
    email: "info@scc-events.com",
    website: "https://www.bmw-berlin-marathon.com",
    imageUrl: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "제주 올레 마라톤",
    titleEn: "Jeju Olle Marathon",
    description: "제주도의 아름다운 해안 올레길을 따라 달리는 특별한 마라톤입니다.",
    eventDate: new Date("2025-04-05"),
    eventTime: "오전 07:00 KST",
    country: "한국",
    region: "제주",
    city: "서귀포",
    venue: "서귀포 올레 시장",
    address: "제주특별자치도 서귀포시 중앙로 62번길 18",
    registrationStatus: "얼리버드",
    registrationStart: new Date("2025-01-01"),
    registrationEnd: new Date("2025-03-20"),
    categories: ["풀 마라톤", "하프 마라톤", "10K", "5K"],
    organizer: "제주 올레 재단",
    phone: "+82 64-762-2190",
    email: "info@jejuolle.org",
    website: "https://www.jejuolle.org",
    imageUrl: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800",
    isFeatured: false,
    isUrgent: false,
  },
  {
    title: "런던 마라톤",
    titleEn: "London Marathon",
    description: "세계에서 가장 큰 자선 마라톤으로, 런던의 명소를 지나갑니다.",
    eventDate: new Date("2025-04-27"),
    eventTime: "오전 10:00 BST",
    country: "유럽",
    region: "영국",
    city: "런던",
    venue: "그리니치 공원",
    address: "Greenwich Park, London SE10 8QY, UK",
    registrationStatus: "접수 중",
    registrationStart: new Date("2024-04-01"),
    registrationEnd: new Date("2025-03-31"),
    categories: ["풀 마라톤"],
    organizer: "London Marathon Events",
    email: "info@londonmarathon.co.uk",
    website: "https://www.tcslondonmarathon.com",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    isFeatured: true,
    isUrgent: false,
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  for (const race of races) {
    await prisma.race.create({
      data: race,
    });
    console.log(`✅ Created race: ${race.title}`);
  }

  console.log("🎉 Seeding completed!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
